---
title: "Rapport du projet"
---
**Noms** : Lancelot Ravier, Danielle El Khoury, Garance Malnoë

Bienvenue sur notre rapport !

Nous avons travaillé sur **trois sous-projets** qui ont chacun une page dédiée :

- Un [jeu de blackjack](blackjack.qmd) en Julia, Python et R jouable depuis le terminal et depuis des interfaces graphiques.

- Un [calculateur de dérivée](dispatching.qmd) en Julia et R, pour mettre en évidence l'utilité du multiple-dispatching de Julia.

- Un [benchmark](benchmark.qmd) entre Julia, Python et C++ à partir du cribble d'Erathostene.


Pour mieux comprendre le processus de création, la page [journal](Journal.qmd) regroupe nos réflexions tout au long du projet.

- **Pour installer le package Julia** :
Ajoutez le package depuis Pkg avec l'url *https://github.com/malnoe/ProjetBlackJack.jl*, appelez le avec `using ProjetBlackJack`. Pour connaitre les fonctions disponibles dans ce package utilisez `help()`.

- **Pour installer le package R** :
Executez le code R suivant :
```r
if (!require("devtools")) install.packages("devtools")
devtools::install_github("da-n-ta/blackjack")
```
