---
title: "Journal de suivi du projet"
format:
  html:
    code-fold: true
    page-layout: full
---
# Entrées du journal

Jeudi 26/09 : Nous avons réfléchi ensemble au projet que nous souhaitions faire. Nous sommes tombés d'accord sur le jeu du blackjack qui nous permet de travailler sur l'apprentissage de R et de Julia avec la possibilité de passer à un affichage graphique du jeu. Nous avons posé les règles du jeu et mis de côté quelques mécaniques telle que le bet (pari avec des jetons), le fait d'avoir plusieurs joueurs et la présence d'un timer. Nous avons également discuté de la structure du projet en Julia et de  comment faire pour coder le jeu. Nous avons créé les fichiers carte.jl, deck.jl, jeu.jl, main.jl, et nous avons tenté - infructueusement - de définir une structure de carte.

Mardi 01/10 : 
Mise en commun de ce qu'a cherché Lancelot durant le weekend : fonction de création de carte, de deck de 52 cartes, de deck de blackjack et mélanger un deck. 
Reflexions sur l'affichage : dash.jl, maki.jl, pluto.jl -> pour faire du html / javascript et avoir quelque chose d'intéractif. Question en cours sur les notions de simple vs multiple dispatching auxquelles Remy a répondues.
Difficultés avec la mise en place de github : on choisit de partir sur un fonctionnement en fork pour séparer notre travail et éviter le problème de merge.

Mercredi 02/10 : Ré-adaptation des fonction de création de deck de blackjack et de mélange de deck. On a créé 2 fonctions shuffle et shuffle!  dans le but d'éviter de devoir recréer le deck de blackjack à chaque partie (dans une session), seulement au début de la session ce qui parait plus optimisé. 
Problématique pour surcharger / étendre les fonction shuffle(!) déjà existantes dans la librairie Random, on l'importe explicitement.
Creation des fonctions de calculs de la valeur d'une main et de tirer une carte.
Première boucle de jeu à 1 joueur basique. On a appris comment demander à un utilisateur de rentrer quelque chose dans le terminal.
Choix d'avoir une seule struct Deck à la fois pour le paquet de carte et pour les mains puisque les deux sont composés d'un Vect de Carte.

Jeudi 03/10:
Mise en commun de ce que chacun a fait Mercredi. On a réparé et amélioré les boucles d'affichage de la valeur d'une main et de la boucle de jeu (problèmes sur les conditions de fin de jeu) et création d'une fonction d'affichage de la main du joueur (les cartes). On a fait plusieurs parties pour tester (et repérer les erreurs). On s'est rendu compte qu'il y avait une version amércaine et une version européenne des règles, on décide de partir sur la version européenne pour le moment car la règle supplémentaire des américains est basée sur la notion de pari / bet que l'on a pas implémentée. On a appris à faire concaténation de String avec s1 * s2.

Mardi 08/10 :
On a appris à créer des pull request et résoudre les conflits sur GitHub à partir du travail qu'avait fait Danielle durant le weekend. Création de module pour les appeler dans pluto. Création du pluto avec les fonctions dedans. Vizagrams -> Création de svg qui s'affichent dans pluto.

Jeudi 10/10 : Version du blackjack en Python. Elle semble + lente mais à tester précisément, avantage c'est qu'on a pas à tapper 2 fois dans la console comme en Julia donc évite les "erreurs" dans le terminal, simple à mettre en place une fois qu'on a fait le travail en Julia.
Version du blackjack dans R: On a vu vraimant la difference entre R et Julia. Julia ne change pas la classe des var en utilisant des fonction, alors que dans R, par exemple: en appliquant la fonction "sample" elle change la classe deck en une classe list pour laisser la classe telle quelle, on a utiliser Deck(sample(...)). On a aussi utiliser explicitement le single dispatching dans R en utilisant pour shuffle la UseMethod.

Mardi 15/10 : Corrections du code pour tout mettre en anglais. On a essayé de faire l'affichage avec Pluto et autres packages d'affichage. 

Jeudi 17/10 : On a une ébauche (bugué) de notebook Pluto pour le jeu. On essaye donc de réparer ça parce que les boutons ne font pas ce que l'on veut (problème de réinitialisation, que modifie le notebook en premier et donc est-ce que les modifications sont bien faites dans l'ordre). Possibilités : passer en markdown, nettoyer le code pour séparer les calculs et l'affichage en faisant des fonctions. On veut aussi implémenter le fait d'afficher des images dans le notebook.
On a également travaillé sur un deuxième projet mettant en oeuvre le simple/multiple dispatching (R/Julia) avec du calcul de dérivées.

Lundi 21/10 : Essai de nettoyer un peu le notebook Pluto. Recherche de moyen de debbug un notebook pluto mais ça n'est pas disponible directement dans Pluto et la librairie (https://github.com/disberd/PlutoVSCodeDebugger.jl) proposant de le faire dans VSCode n'a pas été update depuis plusieurs mois (presque 1an) donc pas moyen de faire le cheminement de penser du notebook sans faire du débug cochon. Première mise à jour du notebook Pluto, sentiment qu'on est pas loin mais toujours soucis de mémoire de la valeur de player_action, à terminer.

Jeudi 24/10 : On a fait une autre version de la fonction jeu, en divisant la fonction en plusieurs fonctions pour pouvoir juste les appeler pour faire run au jeu dans le terminal et dans Pluto.On a fix les boutton hit, stand, new  game dans Pluto avec Vizigram. Toujours un problème dans le Pluto : au début on pensait que c'était parce qu'on n'avait pas le temps de changer la valeur du bouton et donc on a pensé à mettre un sleep dans la boucle pour avoir le temps de cliquer sur les boutons pour changer la valeur de l'input MAIS en fait ça ne marche pas, on ne peut pas update les boutons tant que la fonction game() n'est pas terminée. Autre idée : un wait(condition) pour forcer à changer la valeur du bouton mais c'est un peu flou.

Vacances Toussaint : Fini le benchmark de Python et Julia (appel avec le package PyCall). Boucle pour le jeu dans le terminal sans boucle while : on passe par une fonction récursive. Après avoir joué, on regarde si la partie est terminée, si ça n'est pas le cas alors on rejoue.

Mardi 05/11 : Ajout de la documentation sur toutes les fonctions (hors notebook). Petite correction sur la boucle de jeu pour la condition de fin.

7,12,14/11 : On a travaillé sur le rapport (quarto) et sur le notebook à partir de l'exemple de jeu du package Toto.jl de Remy. On a enfin un pluto notebook fonctionnel.
